name: weekly-cron-job
description: run weekly cron job
inputs:
  ENVIRONMENT:
    description: environment name
    required: true
  DB_SG:
    description: database security group
    required: true
  AWS_ACCESS_KEY_ID:
    description: role to assume
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: role to assume
    required: true
  WORKING_DIR:
    description: The dir of the rails app
    required: false
    default: .
  AWS_REGION:
    description: the region to deploy to
    required: false
    default: us-east-1
  RUBY_VERSION:
    description: the version of ruby to use (optional, in place of .ruby-version file)
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Use ruby version user input if present
      if: ${{ inputs.RUBY_VERSION }}
      shell: bash
      run: echo "RUBY_VERSION=${{ inputs.RUBY_VERSION }}" >> $GITHUB_ENV
    - name: Otherwise, check .ruby-version
      if: ${{ ! inputs.RUBY_VERSION }}
      shell: bash
      working-directory: ${{ inputs.WORKING_DIR }}
      run: echo "RUBY_VERSION=`cat .ruby-version`" >> $GITHUB_ENV
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.126.0
      with:
        bundler-cache: true
        ruby-version: ${{ env.RUBY_VERSION }}
    - name: Add public IP to AWS security group
      uses: sohelamin/aws-security-group-add-ip-action@master
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}
        aws-security-group-id: ${{ inputs.DB_SG }}
        port: '5432'
        to-port: '5432'
        protocol: 'tcp'
        description: 'GitHub Action'
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.WORKING_DIR }}
      run:  bundle install --path vendor/bundle
    - name: Configure AWS credentials AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are pulled from secrets
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}
    - name: Run Weekly Cron Job
      working-directory: rails_api
      run: |
         ls
         aws s3 cp s3://acutity-env/backend/${{ inputs.ENVIRONMENT}} ./.env
         set -o allexport
         source .env
         set +o allexport
         # list of all weekly cron jobs
         bundle exec rake portfolio_snapshot:project_health_count
         bundle exec rake project_snapshot:project
      shell: bash
